name: ${project.artifactId}
main: org.originmc.fbasics.FBasics
version: ${project.version}
description: ${project.description}
authors: [Sudzzy]
website: http://www.originmc.org/
softdepend: [Vault, Factions, MassiveCore]

commands:
    crate:
        description: Access to mystery crates
        aliases: [crates]

    fbasics:
        description: FBasics core command
        aliases: [fb]

    safepromote:
        description: Safely promotes players using a check
        aliases: [sp]

    wilderness:
        description: Teleports the user to a random location
        aliases: [wild]

permissions:
    fbasics.admin:
        default: op
        description: All FBasics permissions for Administrators
        children:
            fbasics.user: true
            fbasics.bypass.antilooter: true
            fbasics.bypass.boat: true
            fbasics.bypass.booklimiter: true
            fbasics.bypass.commands.blocks: true
            fbasics.bypass.commands.cooldowns: true
            fbasics.bypass.commands.economy: true
            fbasics.bypass.commands.glitchable: true
            fbasics.bypass.commands.territory: true
            fbasics.bypass.commands.warmup: true
            fbasics.bypass.dismount: true
            fbasics.bypass.enderpearl: true
            fbasics.bypass.nether: true
            fbasics.bypass.phase: true
            fbasics.commands.crate.change: true
            fbasics.commands.reload: true
            fbasics.commands.safepromote: true

    fbasics.user:
        default: true
        description: Predefined permissions for default players
        children:
            fbasics.commands.crate.balance: true
            fbasics.commands.crate.balance.other: true
            fbasics.commands.crate.open: true
            fbasics.commands.crate.pay: true
            fbasics.commands.wilderness: true